"""add ingredient tracking fields

Revision ID: 8b0e0c6d46b4
Revises: 235943d8a130
Create Date: 2024-12-04 12:55:28.644070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8b0e0c6d46b4'
down_revision: Union[str, None] = '235943d8a130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('min_threshold', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('ingredients', sa.Column('low_stock_alert', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'low_stock_alert')
    op.drop_column('ingredients', 'min_threshold')
    # ### end Alembic commands ###
